name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v3

      - name: Configure dependencies
        if: runner.os == 'Linux'
        run: |  # Per https://github.com/go-gl/glfw#installation
          sudo apt-get update && sudo apt-get install libgl1-mesa-dev xorg-dev

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
